# NUMPY KÜTÜPHANESİ ÖZELLİKLERİ

1-) Numpy bilimsel hesaplamaları hızlı bir şekilde yapmamızı sağlayan bir matematik kütüphanesidir.

2-) Numpy dizileri python listelerine benzer fakat hız ve işlevsellik açısından python listelerinden daha kullanışlıdır.

3-) Numpy dizileri homojen yapıda olmalıdır yani dizi içindeki tüm elemanlar aynı veri tipinden olmalıdır.

In [1]:
# ilk olarak numpy kütüphanemizi dahil ediyoruz
import numpy as np

### ARRAYLER

In [2]:
# numpy kütüphanesi aracılığıyla bir array oluşturabiliriz ...

arr1 = np.array([1,3,7])
arr1

array([1, 3, 7])

In [3]:
# aynı zamanda listeyi direkt olarak koda aktarabiliriz ...

list1 = [2,4,7,10] 
arr1 = np.array(list1)
arr1

array([ 2,  4,  7, 10])

In [4]:
# 1 boyutlu dizi oluşturuyoruz :

arr1 = np.array([3,4,6,9])
arr1

array([3, 4, 6, 9])

In [5]:
# 2 boyutlu dizi oluşturuyoruz :

arr2 = np.array([[11,23,35],[14,19,24]])
arr2

array([[11, 23, 35],
       [14, 19, 24]])

In [6]:
# 3 boyutlu dizi oluşturuyoruz :

arr1 = np.array([[[10,14,17],[20,22,24]] , [[18,19,22] , [42,46,48]]])
arr1

array([[[10, 14, 17],
        [20, 22, 24]],

       [[18, 19, 22],
        [42, 46, 48]]])

In [7]:
# boyut sayısını ndim komutu ile kontrol edebiliriz ...

arr1 = np.array([1,4])
arr2 = np.array([[20,25] , [30,44]])
arr3 = np.array([[[26,27,29],[36,45,55] , [71,77,78],[80,84,88]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [8]:
# boyut sayısını kendimiz belirleyebiliriz ...

arr1 = np.array([6,25,29,37,44] , ndmin = 7)
arr1

array([[[[[[[ 6, 25, 29, 37, 44]]]]]]])

In [9]:
# oluşturduğumuz arrayde 0.indekse ulaşmak istersek aşağıdaki kodu kullanabiliriz ...

arr1 = np.array([21,36,47])
arr1[0]

21

In [10]:
# dizinin elemanları arasında matematiksel işlemler kullanılabilir ...

arr1 = np.array([44,5,22,36,87,99,105])

result1 = arr1[0] + arr1[2]
result2 = arr1[1] - arr1[4]
result3 = arr1[3] * arr1[5]
result4 = arr1[6] // arr1[1]

print(result1)
print(result2)
print(result3)
print(result4)

66
-82
3564
21


In [11]:
# 2 ve 3 boyutlu arraylerin elemanlarınada ulaşmak mümkündür ...

arr1 = np.array([[28, 33], [30, 49]])
arr2 = np.array([[[100, 277, 288], [365, 454, 506], [710, 787, 728], [820, 842, 887]]])

result1 = arr1[0, 1]
result2 = arr1[1, 0]
result3 = arr2[0, 0, 2]
result4 = arr2[0, 1, 1]  

print(result1) 
print(result2)  
print(result3)  
print(result4)  

33
30
288
454


In [12]:
# arange komutu ile arrayin uzunluğunu ayarlayabiliriz ...

arr1 = np.arange(0,10) # 0 dan 10 a kadar (10 dahil değil) array oluşturur ...
arr2 = np.arange(4,22,4) # 4 den 22 ye kadar 4 er 4 er artan array oluşturur ...
arr3 = np.arange(1,56).reshape(11,5) # reshape komutu ile matrisin satır ve sütun sayısını ayarlayabiliriz ...

print(arr1)
print(arr2)
print(arr3)

# !! reshape komutunun içine yazdığımız ilk sayı satır ikinci sayı sütun sayısıdır ve bu iki sayının çarpımı mutlaka arrayin
# eleman sayısına eşit olmalı

[0 1 2 3 4 5 6 7 8 9]
[ 4  8 12 16 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]]


In [13]:
# zeros ve ones komutları ile 0 ve 1 lerden oluşan arrayler oluşturabiliriz ...

arr1 = np.zeros(3) #3 tane 0 lardan oluşan array
arr2 = np.zeros((5,5)) # 5x5 lik 0 lardan oluşan bir array
arr3 = np.ones(6) #6 tane 1 lerdan oluşan array
arr4 = np.ones((7,6)) # 7x6 lik 1 lerdan oluşan bir array

print(arr1)
print("-------------")
print(arr2)
print("-------------")
print(arr3)
print("-------------")
print(arr4)

[0. 0. 0.]
-------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-------------
[1. 1. 1. 1. 1. 1.]
-------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [14]:
# linspace komutu ile birbirlerine eşit uzaklıkta istedğimiz kadar eleman oluşturabiliriz ... 

arr1 = np.linspace(6,45,5)
arr2 = np.linspace(3,24,7)

print(arr1)
print(arr2)

[ 6.   15.75 25.5  35.25 45.  ]
[ 3.   6.5 10.  13.5 17.  20.5 24. ]


### RANDOM

In [15]:
# rand komutu ile 0 ve 1 arasında istedğimiz kadar elemandan oluşan array oluşturabiliriz

arr1 = np.random.rand(5)
arr1

array([0.63134272, 0.92639223, 0.0671901 , 0.43711644, 0.49945394])

In [16]:
# randn komutu ile normal dağılıma uygun array üretebiliriz ...

arr1 = np.random.randn(4,5)
arr1

# randn komutu ile üretilen sayıların ortalaması 0 , standart sapması 1 dir ...

array([[ 0.98436249,  0.95817286,  0.61805631,  0.80160671, -0.11263518],
       [-2.05176033, -0.0082639 , -0.88152804,  1.1035489 ,  0.76538571],
       [-1.79265924,  0.8358534 ,  0.49064471, -2.00093313, -0.562699  ],
       [ 0.4902026 ,  0.00537532, -0.31924763,  2.37056032, -1.73336085]])

In [17]:
# tam sayılar üretmek için randint komutu kullanılır 

arr1 = np.random.randint(10,90,5) # 10 ile 90 arası 5 sayı üretir ...
arr1

array([34, 37, 17, 39, 30])

In [18]:
# seed komutunun içine gönderilen parametre ile herkeste aynı olucak şekilde bir array oluşturulabilir ...

np.random.seed(50) # kim seedin içindeki parametreyi 50 ayarlarsa aynı sonucu alıcak
arr1 = np.random.randint(5,100,8)
arr1

array([53, 16, 38, 99,  9, 75, 75, 27])

In [19]:
# maksimum sayıyı görmek için max , minimum sayıyı görmek için min komutu kullanılır

arr1 = np.random.randint(0,500,50).reshape(10,5)

print(arr1)
print(arr1.max())
print(arr1.min())

[[237 133 258  95 250]
 [ 71 367 452 462 163]
 [348  91 154 218 134]
 [404 299 287  49 341]
 [106 425 320   6 147]
 [130  79 414 105 419]
 [499  26  60 371 322]
 [460 480 323 130 266]
 [496 110 435   0  93]
 [221  94   0 139 414]]
499
0


In [20]:
# argmax ve argmin komutları ile maksimum ve minimum değerlerin indeksini bulabiliriz ...

arr1 = np.random.randint(0,300,10)

print(arr1)
print(arr1.argmax())
print(arr1.argmin())

[154  71  51 156 152  91 174  62 199  36]
8
9


### MATEMATİKSEL İŞLEMLER

In [21]:
arr1 = np.random.randint(0,250,7)

print(arr1)
print("---------------")
print(arr1 + 10)
print("---------------")
print(arr1 - 20)
print("---------------")
print(arr1 * 2)
print("---------------")
print(arr1 / 4)

[228 128 186  43 192 237 147]
---------------
[238 138 196  53 202 247 157]
---------------
[208 108 166  23 172 217 127]
---------------
[456 256 372  86 384 474 294]
---------------
[57.   32.   46.5  10.75 48.   59.25 36.75]


In [22]:
# sum : toplam verir
# mean : ortalama verir
# std : standart sapmayı verir
# var : varyansı verir (standart sapmanın karesi)
# sin : sinüsü verir
# cos : kosinüsü verir
# log : logaritmayı verir

In [23]:
arr1 = np.random.randint(0,500,10)

print(arr1)
print("---------------")
print(arr1.sum())
print("---------------")
print(arr1.mean())
print("---------------")
print(arr1.std())
print("---------------")
print(arr1.var())
print("---------------")
print(np.sin(arr1))
print("---------------")
print(np.cos(arr1))
print("---------------")
print(np.log(arr1))

[314  45 211 385 189 265 285 308 427 101]
---------------
2530
---------------
253.0
---------------
113.06723663378354
---------------
12784.2
---------------
[-0.15859291  0.85090352 -0.49104785  0.98802697  0.48331795  0.89401017
  0.77387159  0.12360304 -0.25379421  0.45202579]
---------------
[ 0.98734406  0.52532199 -0.8711326  -0.15428123  0.87544489  0.44804667
 -0.63334253  0.99233174  0.96725824  0.89200487]
---------------
[5.74939299 3.80666249 5.35185813 5.95324333 5.24174702 5.57972983
 5.65248918 5.73009978 6.05678401 4.61512052]


### İNDEX İŞLEMLERİ

In [24]:
arr1 = np.random.randint(0,100,10)

print(arr1)
print("------")
print(arr1[:]) # tüm değerler 
print("------")
print(arr1[:5]) # ilk değerden 5. indekse kadar olan tüm değerler
print("------")
print(arr1[3:]) # 3.indeksten sonuncu indekse kadar olan tüm değerler
print("------")
print(arr1[4:8]) # 4.indeksten 8.indekse kadar olan tüm değerler

[87 32 19 47 69 92  6 65 36 84]
------
[87 32 19 47 69 92  6 65 36 84]
------
[87 32 19 47 69]
------
[47 69 92  6 65 36 84]
------
[69 92  6 65]


In [25]:
arr1 = np.array([[18,26,33,20,24] , [66,69,77,80,84]])

print(arr1[:,:]) # tüm değerler
print("--------")
print(arr1[0:1 , :]) # sadece ilk grubu yazdırır
print("--------")
print(arr1[1:2 , :]) # sadece ikinci grubu yazdırır
print("---------")
print(arr1[: , 1:4]) # iki grubuda 1.indeksten 4.indekse kadar yazdırır

[[18 26 33 20 24]
 [66 69 77 80 84]]
--------
[[18 26 33 20 24]]
--------
[[66 69 77 80 84]]
---------
[[26 33 20]
 [69 77 80]]


### KOŞUL İFADELERİ

In [26]:
arr1 = np.random.randint(0,100,15)

print(arr1[arr1 > 25]) # sadece 25 den büyük sayıları yazdırır
print("---------")
print(arr1[arr1 < 50]) # sadece 50 den küçük sayıları yazdırır
print("---------")
print(arr1[arr1 % 2 == 0]) # sadece çift sayıları yazdırır

[36 44 53 78 86 43 96 37 30 62 44 43 35]
---------
[36 44  4 43 19 37 30 44 43 35]
---------
[36 44 78  4 86 96 30 62 44]


### EKSTRA ÖZELLİKLER

In [27]:
# copy komutu ile bir arrayi kopyalayabiliriz ...

arr1 = np.random.randint(0,100,10)
arr2 = arr1.copy()

print(arr1)
print("-------")
print(arr2)

[27 50 58 28 31 15  5 52 55 56]
-------
[27 50 58 28 31 15  5 52 55 56]


In [28]:
# where komutu ile aradığımız değerin hangi indeks veya indekslerde olduğunu bulabiliriz ...

arr1 = np.array([0,1,1,2,3,1,2,1])
result = np.where(arr1 == 1)
print(result)

(array([1, 2, 5, 7], dtype=int64),)


In [29]:
# choice ile yazdığımız sayıların yüzdelik olarak dağılımızı belirleyebiliriz ...

arr1 = np.random.choice([0,1,2,3] , p = [0.2 , 0.3 , 0.4 , 0.1] , size = (100))
print(arr1)

[2 2 0 1 0 2 2 2 0 2 2 1 2 1 2 2 1 2 0 3 1 1 3 2 2 3 1 0 1 2 2 3 1 2 2 3 2
 1 2 1 1 2 0 2 2 1 2 1 0 1 2 2 0 3 2 1 2 0 1 3 0 1 2 2 2 2 2 2 2 0 3 1 0 0
 2 0 3 0 2 2 1 3 2 3 2 2 2 0 1 0 0 2 0 1 1 2 2 1 2 1]


In [30]:
# shuffle ile arraydeki elemanları karışık bir şekilde yazabiliriz

arr1 = np.arange(11)
np.random.shuffle(arr1)
print(arr1)

[ 5  8  7  6  1  3 10  4  0  9  2]
